import { useEffect, useMemo, useState } from "react";
import Layout from "../components/layout/Layout";
import { allTours } from "../data/tours";

type TourForm = {
  id: string;
  title: string;
  description: string;
  duration: string;
  image: string;
  category: string;
  featured: boolean;
  locations: string;
  highlights: string;
  advancedJson: string;
};

const STORAGE_KEY = "holiday-tour-admin-tours";
const BACKUP_STORAGE_KEY = "holiday-tour-admin-tours-backup";

const defaultFormState: TourForm = {
  id: "",
  title: "",
  description: "",
  duration: "",
  image: "",
  category: "",
  featured: false,
  locations: "",
  highlights: "",
  advancedJson: "{}",
};

const createTours1FileContent = (toursData: any[]) => {
  return `// Backup generated by the admin panel\nexport const allTours = ${JSON.stringify(toursData, null, 2)};\n`;
};

const downloadBackupFile = (toursData: any[]) => {
  const backupContent = createTours1FileContent(toursData);
  const blob = new Blob([backupContent], { type: "text/javascript;charset=utf-8" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "tours1.js";
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
};

const AdminPage = () => {
  const [tours, setTours] = useState<any[]>([]);
  const [mode, setMode] = useState<"list" | "edit" | "create">("list");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<TourForm>(defaultFormState);
  const [error, setError] = useState<string>("");

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored) {
      try {
        setTours(JSON.parse(stored));
        return;
      } catch (e) {
        console.warn("Invalid admin tour data in localStorage, falling back to source JSON.", e);
      }
    }
    setTours(allTours);
  }, []);

  useEffect(() => {
    if (tours.length > 0) {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(tours, null, 2));
    }
  }, [tours]);

  const selectedTour = useMemo(
    () => tours.find((tour) => tour.id === editingId) || null,
    [editingId, tours]
  );

  useEffect(() => {
    if (!selectedTour) {
      return;
    }

    const advanced = { ...selectedTour };
    delete advanced.id;
    delete advanced.title;
    delete advanced.description;
    delete advanced.duration;
    delete advanced.image;
    delete advanced.category;
    delete advanced.featured;
    delete advanced.locations;
    delete advanced.highlights;

    setForm({
      id: selectedTour.id,
      title: selectedTour.title || "",
      description: selectedTour.description || "",
      duration: selectedTour.duration || "",
      image: selectedTour.image || "",
      category: selectedTour.category || "",
      featured: Boolean(selectedTour.featured),
      locations: Array.isArray(selectedTour.locations)
        ? selectedTour.locations.join(", ")
        : "",
      highlights: Array.isArray(selectedTour.highlights)
        ? selectedTour.highlights.join(", ")
        : "",
      advancedJson: JSON.stringify(advanced, null, 2),
    });
  }, [selectedTour]);

  const startCreate = () => {
    setMode("create");
    setEditingId(null);
    setError("");
    setForm(defaultFormState);
  };

  const startEdit = (id: string) => {
    setMode("edit");
    setEditingId(id);
    setError("");
  };

  const resetForm = () => {
    setMode("list");
    setEditingId(null);
    setError("");
    setForm(defaultFormState);
  };

  const saveTour = () => {
    setError("");
    const id = form.id.trim();
    const title = form.title.trim();
    if (!id || !title) {
      setError("Tour ID and title are required.");
      return;
    }

    const baseTour: any = {
      id,
      title,
      description: form.description,
      duration: form.duration,
      image: form.image,
      category: form.category,
      featured: form.featured,
      locations: form.locations
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean),
      highlights: form.highlights
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean),
    };

    if (form.advancedJson.trim()) {
      try {
        const advancedValue = JSON.parse(form.advancedJson);
        if (advancedValue && typeof advancedValue === "object" && !Array.isArray(advancedValue)) {
          Object.assign(baseTour, advancedValue);
        } else {
          setError("Advanced JSON must be a valid object.");
          return;
        }
      } catch (e) {
        setError("Advanced JSON is not valid JSON.");
        return;
      }
    }

    const exists = tours.some((tour) => tour.id === id);
    if (mode === "create" && exists) {
      setError("A tour with that ID already exists.");
      return;
    }

    const nextTours = [...tours];
    if (mode === "edit") {
      const index = nextTours.findIndex((tour) => tour.id === editingId);
      if (index === -1) {
        setError("Selected tour was not found.");
        return;
      }
      nextTours[index] = baseTour;
    } else {
      nextTours.unshift(baseTour);
    }

    try {
      window.localStorage.setItem(BACKUP_STORAGE_KEY, JSON.stringify(tours, null, 2));
      downloadBackupFile(tours);
    } catch (backupError) {
      console.warn("Could not create backup before saving:", backupError);
    }

    setTours(nextTours);
    resetForm();
  };

  const deleteTour = (id: string) => {
    if (!window.confirm("Delete this tour? This cannot be undone.")) {
      return;
    }
    setTours(tours.filter((tour) => tour.id !== id));
    if (editingId === id) {
      resetForm();
    }
  };

  return (
    <Layout>
      <div className="container mx-auto px-4 py-12">
        <div className="mb-10 flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <h1 className="text-4xl font-playfair font-bold">Admin Panel</h1>
            <p className="mt-2 text-gray-600">
              Manage tour entries loaded from the current JSON dataset. Add, edit, or delete tour records here.
            </p>
          </div>
          <button
            onClick={startCreate}
            className="inline-flex items-center rounded-full bg-travel-orange px-5 py-3 text-sm font-semibold text-white transition hover:bg-orange-600"
          >
            Add New Tour
          </button>
        </div>

        <div className="grid gap-8 lg:grid-cols-[1fr_420px]">
          <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
            <div className="mb-6 flex items-center justify-between gap-3">
              <div>
                <h2 className="text-2xl font-semibold">Tour List</h2>
                <p className="text-sm text-gray-500">{tours.length} tours available</p>
              </div>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm text-gray-700">
                <thead>
                  <tr className="border-b border-gray-200 text-xs uppercase tracking-wide text-gray-500">
                    <th className="px-3 py-3">Title</th>
                    <th className="px-3 py-3">Category</th>
                    <th className="px-3 py-3">Featured</th>
                    <th className="px-3 py-3">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {tours.map((tour) => (
                    <tr key={tour.id} className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="px-3 py-3 align-top text-sm font-medium text-gray-900">{tour.title}</td>
                      <td className="px-3 py-3 align-top text-sm text-gray-600">{tour.category || "—"}</td>
                      <td className="px-3 py-3 align-top text-sm text-gray-600">{tour.featured ? "Yes" : "No"}</td>
                      <td className="px-3 py-3 align-top text-sm text-gray-700">
                        <div className="flex flex-wrap gap-2">
                          <button
                            onClick={() => startEdit(tour.id)}
                            className="rounded-full border border-travel-orange px-3 py-1 text-xs font-semibold text-travel-orange transition hover:bg-orange-50"
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => deleteTour(tour.id)}
                            className="rounded-full border border-red-300 bg-red-50 px-3 py-1 text-xs font-semibold text-red-700 transition hover:bg-red-100"
                          >
                            Delete
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm">
            <div className="mb-6">
              <h2 className="text-2xl font-semibold">{mode === "edit" ? "Edit Tour" : mode === "create" ? "Create Tour" : "Tour Editor"}</h2>
              <p className="text-sm text-gray-500">
                {mode === "list"
                  ? "Select a tour to edit or click Add New Tour to create a new record."
                  : "Update the form and click Save to persist changes."}
              </p>
            </div>

            <div className="space-y-4">
              <div className="grid gap-4 sm:grid-cols-2">
                <label className="block text-sm font-medium text-gray-700">
                  Tour ID
                  <input
                    value={form.id}
                    onChange={(event) => setForm({ ...form, id: event.target.value })}
                    className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                    placeholder="ex: char-dham-yatra"
                  />
                </label>
                <label className="block text-sm font-medium text-gray-700">
                  Title
                  <input
                    value={form.title}
                    onChange={(event) => setForm({ ...form, title: event.target.value })}
                    className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                    placeholder="Tour title"
                  />
                </label>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <label className="block text-sm font-medium text-gray-700">
                  Category
                  <input
                    value={form.category}
                    onChange={(event) => setForm({ ...form, category: event.target.value })}
                    className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                    placeholder="Spiritual, Adventure, etc."
                  />
                </label>
                <label className="block text-sm font-medium text-gray-700">
                  Duration
                  <input
                    value={form.duration}
                    onChange={(event) => setForm({ ...form, duration: event.target.value })}
                    className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                    placeholder="12 Days / 11 Nights"
                  />
                </label>
              </div>

              <label className="block text-sm font-medium text-gray-700">
                Image URL
                <input
                  value={form.image}
                  onChange={(event) => setForm({ ...form, image: event.target.value })}
                  className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                  placeholder="https://example.com/image.jpg"
                />
              </label>

              <label className="block text-sm font-medium text-gray-700">
                Description
                <textarea
                  value={form.description}
                  onChange={(event) => setForm({ ...form, description: event.target.value })}
                  rows={4}
                  className="mt-2 w-full rounded-3xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                  placeholder="Tour description"
                />
              </label>

              <div className="grid gap-4 sm:grid-cols-2">
                <label className="block text-sm font-medium text-gray-700">
                  Locations (comma separated)
                  <input
                    value={form.locations}
                    onChange={(event) => setForm({ ...form, locations: event.target.value })}
                    className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                    placeholder="Delhi, Haridwar, Barkot"
                  />
                </label>
                <label className="block text-sm font-medium text-gray-700">
                  Highlights (comma separated)
                  <input
                    value={form.highlights}
                    onChange={(event) => setForm({ ...form, highlights: event.target.value })}
                    className="mt-2 w-full rounded-2xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                    placeholder="Ganga Aarti, Himalayan views"
                  />
                </label>
              </div>

              <div className="flex items-center gap-3">
                <input
                  id="featured-toggle"
                  type="checkbox"
                  checked={form.featured}
                  onChange={(event) => setForm({ ...form, featured: event.target.checked })}
                  className="h-4 w-4 rounded border-gray-300 text-travel-orange focus:ring-travel-orange"
                />
                <label htmlFor="featured-toggle" className="text-sm font-medium text-gray-700">
                  Mark as featured
                </label>
              </div>

              <label className="block text-sm font-medium text-gray-700">
                Advanced JSON (optional)
                <textarea
                  value={form.advancedJson}
                  onChange={(event) => setForm({ ...form, advancedJson: event.target.value })}
                  rows={6}
                  className="mt-2 w-full rounded-3xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 outline-none transition focus:border-travel-orange focus:ring-2 focus:ring-travel-orange/20"
                  placeholder='e.g. { "contact": { "phone": ["+91-..."], "email": ["...@gmail.com"] } }'
                />
              </label>

              {error ? <p className="text-sm text-red-600">{error}</p> : null}

              <div className="flex flex-col gap-3 sm:flex-row sm:justify-end">
                <button
                  onClick={resetForm}
                  type="button"
                  className="rounded-full border border-gray-300 px-5 py-3 text-sm font-semibold text-gray-700 transition hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  onClick={saveTour}
                  type="button"
                  className="rounded-full bg-travel-orange px-5 py-3 text-sm font-semibold text-white transition hover:bg-orange-600"
                >
                  Save Tour
                </button>
              </div>
            </div>
          </section>
        </div>
      </div>
    </Layout>
  );
};

export default AdminPage;
